/**
 * Sync techniques/ and mitre_ttp_mapping.json with the current MITRE
 * ATT&CK Enterprise STIX bundle.
 *
 * For every active (non-revoked, non-deprecated) technique:
 *   • Ensure techniques/T####/ exists.
 *   • (Re)write techniques/T####/README.md from STIX — so MITRE renames,
 *     description edits, added platforms, etc. propagate into the repo.
 *
 * Also regenerates:
 *   • mitre_ttp_mapping.json          — parent technique → tactic (phase_name)
 *   • .mitre-attack-version           — the STIX collection version, for traceability
 *
 * Hunt files sitting alongside README.md in each folder are left untouched.
 */

const fs = require("fs");
const path = require("path");
const fetch = require("node-fetch");

// attack-stix-data is the current, supported STIX 2.1 source (mitre/cti is
// legacy STIX 2.0 and is missing the x-mitre-collection version metadata).
const STIX_URL =
  "https://raw.githubusercontent.com/mitre-attack/attack-stix-data/master/enterprise-attack/enterprise-attack.json";

const ROOT         = path.resolve(__dirname, "..", "..");
const TECH_DIR     = path.join(ROOT, "techniques");
const MAPPING_FILE = path.join(ROOT, "mitre_ttp_mapping.json");
const VERSION_FILE = path.join(ROOT, ".mitre-attack-version");

function capFirst(s) {
  return s ? s.charAt(0).toUpperCase() + s.slice(1) : s;
}

function tacticDisplay(phase) {
  return phase.split("-").map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(" ");
}

function buildReadme(technique, id, mitreUrl, version, bundleName) {
  const name = technique.name || id;
  const description = (technique.description || "_No description available._").trim();

  const tacticLabels = (technique.kill_chain_phases || [])
    .filter(kc => kc.kill_chain_name === "mitre-attack")
    .map(kc => tacticDisplay(kc.phase_name));

  const platforms   = technique.x_mitre_platforms   || [];
  const dataSources = technique.x_mitre_data_sources || [];
  const detection   = (technique.x_mitre_detection || "").trim();
  const isSub       = id.includes(".");

  const sections = [];
  sections.push(`# ${name}`);
  sections.push("");
  sections.push(`**Technique ID:** \`${id}\`${isSub ? " (sub-technique)" : ""}  `);
  sections.push(`**Tactic(s):** ${tacticLabels.join(", ") || "—"}  `);
  sections.push(`**Platforms:** ${platforms.join(", ") || "—"}  `);
  sections.push(`**MITRE Reference:** [${mitreUrl}](${mitreUrl})`);
  sections.push("");
  sections.push("## Description");
  sections.push("");
  sections.push(description);

  if (dataSources.length) {
    sections.push("");
    sections.push("## Data Sources");
    sections.push("");
    for (const d of dataSources) sections.push(`- ${d}`);
  }

  if (detection) {
    sections.push("");
    sections.push("## Detection Guidance");
    sections.push("");
    sections.push(detection);
  }

  sections.push("");
  sections.push("---");
  sections.push("");
  sections.push(
    `_Auto-generated from ${bundleName} v${version}. ` +
    `Do not edit this file directly — it is overwritten on every sync. ` +
    `Add hunts as sibling \`T####-*.md\` files in this folder._`
  );
  sections.push("");
  return sections.join("\n");
}

async function main() {
  console.log(`Fetching ${STIX_URL}`);
  const res = await fetch(STIX_URL);
  if (!res.ok) throw new Error(`MITRE fetch failed: ${res.status} ${res.statusText}`);
  const stix = await res.json();

  const collection = stix.objects.find(o => o.type === "x-mitre-collection");
  const version    = collection?.x_mitre_version || "unknown";
  const bundleName = collection?.name || "Enterprise ATT&CK";

  // Active techniques only
  const techniques = stix.objects.filter(o =>
    o.type === "attack-pattern" &&
    !o.revoked &&
    !o.x_mitre_deprecated
  );

  fs.mkdirSync(TECH_DIR, { recursive: true });

  let created   = 0;
  let rewritten = 0;
  let unchanged = 0;
  let skipped   = 0;
  const mapping = [];

  for (const t of techniques) {
    const mitreRef = (t.external_references || []).find(r => r.source_name === "mitre-attack");
    if (!mitreRef || !mitreRef.external_id) { skipped++; continue; }

    const id     = mitreRef.external_id;
    const folder = path.join(TECH_DIR, id);
    const folderExisted = fs.existsSync(folder);
    if (!folderExisted) fs.mkdirSync(folder, { recursive: true });

    // Mapping: parents only (sub-techniques inherit their parent's tactic column)
    if (!id.includes(".")) {
      const phases = (t.kill_chain_phases || [])
        .filter(kc => kc.kill_chain_name === "mitre-attack")
        .map(kc => capFirst(kc.phase_name));
      for (const tactic of phases) {
        mapping.push({ technique_id: id, tactic });
      }
    }

    const readmePath    = path.join(folder, "README.md");
    const nextContent   = buildReadme(t, id, mitreRef.url, version, bundleName);
    const existing      = fs.existsSync(readmePath)
      ? fs.readFileSync(readmePath, "utf8")
      : null;

    if (existing === nextContent) {
      unchanged++;
      continue;
    }
    fs.writeFileSync(readmePath, nextContent);
    if (existing === null) created++;
    else                   rewritten++;
  }

  // Deduplicate mapping entries, sort for stable diffs
  const uniq = new Map();
  for (const m of mapping) uniq.set(`${m.technique_id}|${m.tactic}`, m);
  const mappingArr = Array.from(uniq.values())
    .sort((a, b) => a.technique_id.localeCompare(b.technique_id) ||
                    a.tactic.localeCompare(b.tactic));

  fs.writeFileSync(MAPPING_FILE, JSON.stringify(mappingArr, null, 2) + "\n");
  fs.writeFileSync(VERSION_FILE, version + "\n");

  console.log(`${bundleName} v${version}`);
  console.log(`  techniques processed : ${techniques.length}`);
  console.log(`  skipped (no mitre id): ${skipped}`);
  console.log(`  READMEs created      : ${created}`);
  console.log(`  READMEs rewritten    : ${rewritten}`);
  console.log(`  READMEs unchanged    : ${unchanged}`);
  console.log(`  mapping entries      : ${mappingArr.length}`);
}

main().catch(err => {
  console.error("Error:", err);
  process.exit(1);
});
