version: 2
name: "Test Form"
description: "A minimal Issue Form."
title: "Test Issue"
labels: []
assignees: []

body:
  - type: markdown
    attributes:
      value: "Hello, world!"

  - type: input
    id: example_field
    attributes:
      label: "Example field"
      description: "Please type something."
    validations:
      required: true
