name: Update Threat Hunt on Completion
on:
  issues:
    types: [edited, closed]

jobs:
  update-technique:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install Dependencies
        run: |
          npm install @octokit/rest node-fetch@2

      - name: Run updateThreatHunt Script
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
          BRANCH_NAME: main  # Change this if your default branch is not "main"
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_EVENT_PATH: ${{ github.event_path }}
        run: node .github/scripts/updateThreatHunt.js
